/*
 * Copyright (C) 2008 by Steve Krulewitz <skrulx@gmail.com>
 * Licensed under GPLv2 or later, see file LICENSE in the xpi for details.
 */

#include "nsISupports.idl"
#include "nsIObserver.idl"

[scriptable, uuid(44d20ff9-c84f-47f8-87a0-187a26503444)]
interface sbIStatusListener : nsISupports
{
  void onError(in AString aMessage);
  void onNewExternalIpAddress(in AString aIpAddress);
};

[scriptable, uuid(26042e79-54e6-488c-844c-9e1672d5c296)]
interface sbIPortMappingListener : nsISupports
{
  void onAdded(in unsigned short aLocal, in unsigned short aRemote);
  void onRemoved(in unsigned short aLocal);
  void onError(in unsigned short aLocal, in unsigned short aRemote);
};

[scriptable, uuid(3250414e-e740-4219-a131-21a9d7208e22)]
interface sbIInternetGatewayService : nsISupports
{
  void addStatusListener(in sbIStatusListener aListener);
  void removeStatusListener(in sbIStatusListener aListener);

  void addPortMapping(in unsigned short aLocal,
                      in unsigned short aRemote,
                      in sbIPortMappingListener aListener);
  void removePortMapping(in unsigned short aLocal);
};
