/*
 * Copyright (C) 2008 by Steve Krulewitz <skrulx@gmail.com>
 * Licensed under GPLv2 or later, see file LICENSE in the xpi for details.
 */
#include "nsISupports.idl"

[scriptable, uuid(832d93ab-fe57-4a34-9c9a-55372a6b076e)]
interface stIUdpMulticastCallback : nsISupports
{
  void receive(in unsigned long aRecieveLength,
               [array, size_is(aRecieveLength)] in PRUint8 aRecieveBytes);
  void done(in nsresult aResult);
};

[scriptable, uuid(bea3a6ea-ee1c-4412-8d07-05459a4aed32)]
interface stINetUtils : nsISupports
{
  void sendUdpMulticast(in ACString aIpAddres,
                        in unsigned short aPort,
                        in unsigned long long aTimeout,
                        in unsigned long aSendLength,
                        [array, size_is(aSendLength)] in PRUint8 aSendBytes,
                        in stIUdpMulticastCallback aCallback);
};
